server:
  port: 8080

spring:
  datasource:
    url: ${settings.jdbc.url}
    username: ${settings.jdbc.username}
    password: ${settings.jdbc.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: jdbc

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
